/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Schema {
  command: string;
  subcommands: {
    command: string;
    args: {
      name?: string;
      completion: Completion;
    }[];
    flags: (
      | {
          type: {
            [k: string]: any;
          };
          [k: string]: any;
        }
      | {
          type: {
            [k: string]: any;
          };
          [k: string]: any;
        }
    )[];
  }[];
}
export interface Completion {
  type: string;
  [k: string]: any;
}
